const HTTP_STATUS_BAD_REQUEST_ERROR = 400;
const HTTP_STATUS_NOT_FOUND = 404;
const HTTP_STATUS_INTERNAL_SERVER_ERROR = 500;
const HTTP_STATUS_CREATED = 201;
const HTTP_STATUS_OK = 200;

module.exports = {
  HTTP_STATUS_BAD_REQUEST_ERROR,
  HTTP_STATUS_NOT_FOUND,
  HTTP_STATUS_INTERNAL_SERVER_ERROR,
  HTTP_STATUS_CREATED,
  HTTP_STATUS_OK,
};